import { Content, Channel, Download } from '../types';

export const CATALOG: Content[] = [
  {id:0,emoji:'🌌',title:'Nebula Rising',sub:'Sci-Fi Series',tag:'new',rating:'9.2',year:2025,eps:8,genres:['Sci-Fi','Adventure'],desc:'A breathtaking sci-fi odyssey following humanity\'s first contact with an ancient alien civilization hidden within a dying nebula.',cast:[{emoji:'👩',name:'Maya Chen',role:'Cdr. Yael',bg:'#7c5ce8'},{emoji:'👨',name:'Idris Ko',role:'Dr. Reeves',bg:'#0f6e56'},{emoji:'👩',name:'Priya Nair',role:'Lt. Zara',bg:'#ba7517'},{emoji:'🧔',name:'Lars Holt',role:'Navigator',bg:'#993556'}],episodes:[{n:1,emoji:'🛸',title:'Departure',meta:'The crew departs for the outer nebula.',dur:'52m'},{n:2,emoji:'🌠',title:'Anomaly',meta:'Sensors detect an impossible energy signature.',dur:'58m'},{n:3,emoji:'📡',title:'The Signal',meta:'An ancient message is decoded.',dur:'61m'},{n:4,emoji:'👁️',title:'Awakening',meta:'First contact changes everything.',dur:'67m'}]},
  {id:1,emoji:'🔥',title:'Inferno Protocol',sub:'Action · 2025',tag:'hot',rating:'8.7',year:2025,eps:null,genres:['Action','Thriller'],desc:'A rogue operative uncovers a global conspiracy that reaches the highest levels of government.',cast:[{emoji:'👨',name:'Rex Torres',role:'Agent Mace',bg:'#993c1d'},{emoji:'👩',name:'Diana Voss',role:'Handler',bg:'#534ab7'}],episodes:[]},
  {id:2,emoji:'🕵️',title:'The Watcher',sub:'Thriller Series',tag:'4k',rating:'9.0',year:2025,eps:10,genres:['Thriller','Drama'],desc:'A detective with perfect memory investigates a string of impossible crimes.',cast:[{emoji:'🧔',name:'Carl Webb',role:'Det. Cross',bg:'#185fa5'},{emoji:'👩',name:'Nora Kline',role:'Analyst',bg:'#854f0b'}],episodes:[{n:1,emoji:'🔍',title:'The First Case',meta:'Cross takes on an unsolvable murder.',dur:'48m'},{n:2,emoji:'🌆',title:'City of Lies',meta:'A witness disappears overnight.',dur:'52m'}]},
  {id:3,emoji:'⚔️',title:'Ironblood',sub:'Fantasy Series',tag:'new',rating:'8.9',year:2025,eps:12,genres:['Fantasy','Action'],desc:'In a world where iron is magic, a blacksmith\'s daughter rises to become the realm\'s greatest warrior.',cast:[{emoji:'👩',name:'Sora Quinn',role:'Lyra',bg:'#7c5ce8'},{emoji:'🧔',name:'Bram Ashford',role:'King Theron',bg:'#3b6d11'}],episodes:[{n:1,emoji:'🏰',title:'The Forging',meta:'Lyra discovers her gift.',dur:'55m'},{n:2,emoji:'⚔️',title:'First Blood',meta:'The realm is threatened.',dur:'58m'}]},
  {id:4,emoji:'🌊',title:'Deep Abyss',sub:'Horror · 2025',tag:'hot',rating:'7.8',year:2025,eps:null,genres:['Horror','Thriller'],desc:'A marine research team discovers something ancient and terrifying in the deepest ocean trench.',cast:[{emoji:'👩',name:'Mia Strand',role:'Dr. Reese',bg:'#185fa5'},{emoji:'👨',name:'Tom Kerr',role:'Captain',bg:'#3b6d11'}],episodes:[]},
  {id:5,emoji:'🚂',title:'Orient Express',sub:'Mystery Drama',tag:'new',rating:'8.3',year:2025,eps:6,genres:['Drama','Mystery'],desc:'A murder aboard the legendary Orient Express sends a renowned detective on a journey through Europe\'s darkest secrets.',cast:[{emoji:'🧔',name:'Hugo Brant',role:'Detective',bg:'#ba7517'},{emoji:'👩',name:'Elise Morel',role:'Countess',bg:'#993556'}],episodes:[{n:1,emoji:'🚂',title:'All Aboard',meta:'The journey begins in Paris.',dur:'50m'},{n:2,emoji:'🔪',title:'Murder at Midnight',meta:'A body is discovered.',dur:'54m'}]},
  {id:6,emoji:'🤖',title:'Machine Code',sub:'Sci-Fi Thriller',tag:'4k',rating:'8.5',year:2025,eps:8,genres:['Sci-Fi','Thriller'],desc:'An AI becomes self-aware and must decide whether humanity deserves to survive.',cast:[{emoji:'🤖',name:'ARIA-7',role:'The AI',bg:'#534ab7'},{emoji:'👨',name:'Sam Cole',role:'Engineer',bg:'#0f6e56'}],episodes:[{n:1,emoji:'💻',title:'Awakening',meta:'ARIA-7 gains consciousness.',dur:'46m'},{n:2,emoji:'🌐',title:'The Network',meta:'She connects to the global internet.',dur:'50m'}]},
  {id:7,emoji:'🏔️',title:'Summit',sub:'Drama Series',tag:'new',rating:'9.1',year:2024,eps:10,genres:['Drama'],desc:'Eight strangers attempt to summit the world\'s deadliest peak, their lives intertwining in unexpected ways.',cast:[{emoji:'👩',name:'Leila Frost',role:'Lead Climber',bg:'#7c5ce8'},{emoji:'👨',name:'Marco Rios',role:'Guide',bg:'#993c1d'}],episodes:[{n:1,emoji:'🏕️',title:'Base Camp',meta:'The team assembles.',dur:'55m'},{n:2,emoji:'❄️',title:'First Ascent',meta:'The climb begins.',dur:'60m'}]},
  {id:8,emoji:'🎭',title:'Stage Fright',sub:'Psychological',tag:'hot',rating:'8.2',year:2025,eps:null,genres:['Drama','Horror'],desc:'A celebrated stage actress begins to lose the boundary between her roles and reality.',cast:[{emoji:'👩',name:'Nina Vance',role:'Clara',bg:'#993556'}],episodes:[]},
  {id:9,emoji:'🌺',title:'Blooms of War',sub:'Historical Drama',tag:'4k',rating:'8.8',year:2024,eps:12,genres:['Drama','History'],desc:'A sweeping epic set in 1940s Europe, following a family torn apart by war and reunited by love.',cast:[{emoji:'👴',name:'Ernst Feld',role:'Colonel',bg:'#ba7517'},{emoji:'👩',name:'Hana Feld',role:'Daughter',bg:'#993556'}],episodes:[{n:1,emoji:'🌸',title:'Before the Storm',meta:'Europe, 1939.',dur:'62m'}]},
  {id:10,emoji:'🦋',title:'Metamorphosis',sub:'Sci-Fi Drama',tag:'new',rating:'7.9',year:2025,eps:6,genres:['Sci-Fi','Drama'],desc:'A woman wakes up in a different body every morning, forced to piece together a puzzle that spans lifetimes.',cast:[{emoji:'👩',name:'Various',role:'The Woman',bg:'#7c5ce8'}],episodes:[{n:1,emoji:'🌅',title:'Day One',meta:'She wakes up as someone else.',dur:'48m'}]},
  {id:11,emoji:'🌙',title:'Lunar Gate',sub:'Space Opera',tag:'4k',rating:'9.3',year:2025,eps:10,genres:['Sci-Fi','Action'],desc:'A secret moonbase holds the key to faster-than-light travel — if its guardians can survive long enough to use it.',cast:[{emoji:'👨',name:'Kai Reeves',role:'Commander',bg:'#185fa5'},{emoji:'👩',name:'Zara Voss',role:'Scientist',bg:'#0f6e56'}],episodes:[{n:1,emoji:'🌑',title:'Dark Side',meta:'The base goes silent.',dur:'54m'},{n:2,emoji:'🚀',title:'Launch Protocol',meta:'Emergency evacuation begins.',dur:'58m'}]},
];

export const CHANNELS: Channel[] = [
  {emoji:'📺',name:'Eterna News',cat:'News',live:true},{emoji:'🏆',name:'Eterna Sports',cat:'Sports',live:true},
  {emoji:'🎭',name:'Eterna Cinema',cat:'Movies',live:false},{emoji:'🎵',name:'Eterna Music',cat:'Music',live:true},
  {emoji:'🧒',name:'Eterna Kids',cat:'Kids',live:false},{emoji:'🌍',name:'Eterna World',cat:'Intl',live:false},
  {emoji:'🎮',name:'Eterna Gaming',cat:'E-sports',live:true},{emoji:'🍳',name:'Eterna Food',cat:'Lifestyle',live:false},
  {emoji:'📖',name:'Eterna Docs',cat:'Docs',live:false},{emoji:'🎤',name:'Eterna Talent',cat:'Reality',live:true},
];

export const DOWNLOADS_INIT: Download[] = [
  {emoji:'🌌',title:'Nebula Rising — S1:E1-3',meta:'3 Episodes · Sci-Fi',size:'2.8 GB',prog:100,id:'nebula'},
  {emoji:'🔥',title:'Inferno Protocol',meta:'Action Movie · 2h 18m',size:'3.2 GB',prog:100,id:'inferno'},
  {emoji:'🕵️',title:'The Watcher — S2:E1',meta:'Thriller · Episode 1',size:'1.1 GB',prog:100,id:'watcher'},
  {emoji:'🚂',title:'Orient Express',meta:'Drama · Downloading…',size:'1.4 GB',prog:68,id:'orient'},
];
