import { Content, Channel, Download } from '../types';

export const CATALOG: Content[] = [
  {id:0,coverUrl:'https://upload.wikimedia.org/wikipedia/commons/8/8f/Sintel_poster.jpg',title:'Sintel',sub:'Open-Source Fantasy',tag:'new',rating:'9.5',year:2024,eps:null,genres:['Fantasy','Adventure','CGI'],desc:'The saga of a lonely young woman who searches for her companion dragon in a beautiful but dangerous fantasy world.',cast:[{emoji:'👩',name:'Sintel',role:'Sintel',bg:'#00D9FF'}],episodes:[],videoUrl:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'},
  {id:1,coverUrl:'https://resizing.flixster.com/MXrpgQtRGjkZ3XMb_BwkPonAWbE=/fit-in/352x330/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p26727706_b_v13_aa.jpg',title:'Aníkúlápó',sub:'Fantasy Drama',tag:'new',rating:'9.2',year:2025,eps:8,genres:['Fantasy','Drama'],desc:'An epic tale of love, betrayal, and mysticism in the ancient Oyo Empire.',cast:[{emoji:'👩',name:'Sola',role:'Arolake',bg:'#7c5ce8'}],episodes:[],videoUrl:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'},
  {id:2,coverUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuXxd1Ac-DeglLiAqVsvW2dkmLYb9FteNH-g&s',title:'Inception',sub:'Sci-Fi Action',tag:'hot',rating:'8.7',year:2010,eps:null,genres:['Action','Sci-Fi'],desc:'A thief who enters the dreams of others to steal their secrets gets a final chance at redemption.',cast:[{emoji:'👨',name:'Leo',role:'Cobb',bg:'#993c1d'}],episodes:[],videoUrl:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'},
  {id:3,coverUrl:'https://resizing.flixster.com/0AALvhDfiXVIuYcVc1iAYSJBG-Q=/206x305/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p20487596_b_v13_aa.jpg',title:'King of Boys',sub:'Crime Thriller',tag:'4k',rating:'9.0',year:2018,eps:10,genres:['Thriller','Drama'],desc:'A businesswoman and philanthropist with a checkered past is drawn into a power struggle.',cast:[{emoji:'🧔',name:'Shola',role:'Eniola',bg:'#185fa5'}],episodes:[],videoUrl:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'},
  {id:4,coverUrl:'https://m.media-amazon.com/images/S/pv-target-images/8753733ac616155963cc440c3cf5367f45d7685b672c5b9c35bc7f182aec17c4.jpg',title:'The Dark Knight',sub:'Action Thriller',tag:'new',rating:'8.9',year:2008,eps:null,genres:['Action','Hero'],desc:'Batman raises the stakes in his war on crime when a menace known as the Joker wreaks havoc.',cast:[{emoji:'🧔',name:'Christian',role:'Bruce',bg:'#3b6d11'}],episodes:[],videoUrl:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'},
  {id:5,coverUrl:'https://m.media-amazon.com/images/I/71s3cEqEZTL._AC_UF894,1000_QL80_.jpg',title:'Avatar: The Way of Water',sub:'Sci-Fi',tag:'hot',rating:'7.8',year:2022,eps:null,genres:['Sci-Fi','Action'],desc:'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora.',cast:[{emoji:'👩',name:'Zoe',role:'Neytiri',bg:'#185fa5'}],episodes:[],videoUrl:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'},
  {id:6,coverUrl:'https://m.media-amazon.com/images/M/MV5BZDJhN2RlYjItNGE4MC00NGYwLWE0ZGMtNWEwMTNkYTZiZTg4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',title:'Sista',sub:'Drama',tag:'new',rating:'8.3',year:2023,eps:6,genres:['Drama'],desc:'A struggling single mother faces her past when the father of her children returns.',cast:[{emoji:'👩',name:'Kehinde',role:'Sista',bg:'#993556'}],episodes:[],videoUrl:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'},
  {id:7,coverUrl:'https://s3.amazonaws.com/nightjarprod/content/uploads/sites/238/2024/01/04112042/cBDoFHJVcZqAonkTyhN9sMEggi5-scaled.jpg',title:'Dune: Part Two',sub:'Sci-Fi Epic',tag:'4k',rating:'8.5',year:2024,eps:null,genres:['Sci-Fi','Adventure'],desc:'Paul Atreides unites with Chani and the Fremen while on a warpath of revenge.',cast:[{emoji:'👨',name:'Tim',role:'Paul',bg:'#0f6e56'}],episodes:[],videoUrl:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4'},
  {id:8,coverUrl:'https://m.media-amazon.com/images/M/MV5BMGRhOTlhYzMtODMwNy00YjExLWJhNjgtMmNhMzQ5NjM4YWMxXkEyXkFqcGc@._V1_.jpg',title:'Jagun Jagun',sub:'Action Action',tag:'new',rating:'9.1',year:2023,eps:null,genres:['Action'],desc:'A young man determined to become a powerful warrior joins an elite army.',cast:[{emoji:'👨',name:'Lateef',role:'Gbotija',bg:'#993c1d'}],episodes:[],videoUrl:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'},
  {id:9,coverUrl:'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTaJ4iwFC3tG7YzKFGsI3P9LcHnjV1q0-SqTM4V5Edlxw_mfiyWPNNmCPVbQveeWlYyRgFPbpRZ729O5456wGx7CPW_mDfoaC7slPprNEXnKAz1i2_OlnXr&usqp=CAc',title:'Joker',sub:'Psychological Thriller',tag:'hot',rating:'8.2',year:2019,eps:null,genres:['Drama','Thriller'],desc:'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society.',cast:[{emoji:'👨',name:'Joaquin',role:'Arthur',bg:'#993556'}],episodes:[],videoUrl:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'},
  {id:10,coverUrl:'https://m.media-amazon.com/images/M/MV5BODIwZjA3ZGQtYWJhYS00ZDA1LTljMDEtNGVmNTE0ZjJmZWY5XkEyXkFqcGc@._V1_.jpg',title:'Citation',sub:'Thriller Drama',tag:'4k',rating:'8.8',year:2020,eps:null,genres:['Drama'],desc:'A bright student in Nigeria takes on the academic establishment when she reports a professor.',cast:[{emoji:'👩',name:'Temi',role:'Moremi',bg:'#993556'}],episodes:[],videoUrl:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4'},
  {id:11,coverUrl:'https://m.media-amazon.com/images/M/MV5BOGIxNTc3ZDAtMjdhNi00YWYwLTg1MjgtNzM2NjhkNDhhMTljXkEyXkFqcGc@._V1_.jpg',title:'Gangs of Lagos',sub:'Action Crime',tag:'new',rating:'7.9',year:2023,eps:null,genres:['Crime','Action'],desc:'A group of friends who each have to navigate their own destiny, growing up on the bustling streets.',cast:[{emoji:'👨',name:'Tobi',role:'Obalola',bg:'#7c5ce8'}],episodes:[],videoUrl:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4'},
  {id:12,coverUrl:'https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg',title:'Oppenheimer',sub:'Historical Drama',tag:'4k',rating:'9.3',year:2023,eps:null,genres:['Drama','History'],desc:'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',cast:[{emoji:'👨',name:'Cillian',role:'Oppie',bg:'#185fa5'}],episodes:[],videoUrl:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'},
];

export const CHANNELS: Channel[] = [
  {emoji:'📺',name:'Eterna News',cat:'News',live:true},{emoji:'🏆',name:'Eterna Sports',cat:'Sports',live:true},
  {emoji:'🎭',name:'Eterna Cinema',cat:'Movies',live:false},{emoji:'🎵',name:'Eterna Music',cat:'Music',live:true},
  {emoji:'🧒',name:'Eterna Kids',cat:'Kids',live:false},{emoji:'🌍',name:'Eterna World',cat:'Intl',live:false},
  {emoji:'🎮',name:'Eterna Gaming',cat:'E-sports',live:true},{emoji:'🍳',name:'Eterna Food',cat:'Lifestyle',live:false},
  {emoji:'📖',name:'Eterna Docs',cat:'Docs',live:false},{emoji:'🎤',name:'Eterna Talent',cat:'Reality',live:true},
];

export const DOWNLOADS_INIT: Download[] = [
  {emoji:'🌌',title:'Nebula Rising — S1:E1-3',meta:'3 Episodes · Sci-Fi',size:'2.8 GB',prog:100,id:'nebula'},
  {emoji:'🔥',title:'Inferno Protocol',meta:'Action Movie · 2h 18m',size:'3.2 GB',prog:100,id:'inferno'},
  {emoji:'🕵️',title:'The Watcher — S2:E1',meta:'Thriller · Episode 1',size:'1.1 GB',prog:100,id:'watcher'},
  {emoji:'🚂',title:'Orient Express',meta:'Drama · Downloading…',size:'1.4 GB',prog:68,id:'orient'},
];
